version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: fingerprint_redis
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local 